name: web-ci-cd
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Flutter pub get
        run: flutter pub get
      - name: Analyze & Test
        run: |
          flutter analyze
          flutter test --coverage || true
      - name: Build Web (with base-href for GitHub Pages)
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          flutter build web --release --base-href "/$REPO_NAME/"
      - name: Create 404.html for SPA
        run: |
          cp build/web/index.html build/web/404.html
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages